# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('we_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weather_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='weather_start_date',
            field=models.DateField(),
        ),
    ]
